name: Spring Build and Analyze
on: [pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
  build:
    needs: changes
    if: ${{ needs.changes.outputs.backend }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available
      - name: Shutdown Ubuntu MariaDB
        run: sudo service mysql stop
      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.11
        with:
           mysql database: more
           mysql root password: 1234
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set Credentials
        run: |
          cd backend
          mkdir -p src/main/resources
          echo ${{ secrets.APPLICATION_YML }} | base64 --decode > src/main/resources/application.yml
